import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import AuthProvider from '../components/AuthProvider'
import { CrispProvider } from '@/components/crisp-provider'
import { getApiLimitCount } from "../app/utils/api-limit"; // Update the path accordingly

import { useSession } from 'next-auth/react';

import { getCount } from './getApiCountpage/page'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
//   const {data, status}  = useSession()

//   // Get the user's email from the session data
//   const userEmail = data?.user?.email;

//  const apiLimitCount = getApiLimitCount(userEmail)
  // const count = getCount();

  return (
    <html lang="en">
      <CrispProvider/>
      <body className={inter.className}>
        <AuthProvider>
          <div className="flex overflow-hidden">
              
          
              <Navbar/>
              
              <div className="flex-1">
                {children}
                
              </div>
            </div>

        </AuthProvider>
        
        
      </body>
    </html>
  )
}
